# window
confirm_os_window_close 0

# Font
font_family JetBrainsMono Nerd
font_size 12.0
  
# Window Appearance
background_opacity 0.75

# Cursor
cursor #f5e0dc

# Colors
foreground #cdd6f4
background #1e1e2e

selection_foreground #1e1e2e
selection_background #f5e0dc

active_border_color #b4befe # Cursor + misc
inactive_border_color #6c7086 # Cursor + misc

color0 #45475a # Color Black
color8 #585b70 # Color Black

color1 #f38ba8 # Color Red
color9 #f38ba8 # Color Red
  
color2 #a6e3a1 # Color Green
color10 #a6e3a1 # Color Green

color3 #f9e2af # Color Yellow
color11 #f9e2af # Color Yellow

color4 #89b4fa # Color Blue
color12 #89b4fa # Color Blue

color5 #f5c2e7 # Color Magenta
color13 #f5c2e7 # Color Magenta

color6 #94e2d5 # Color Cyan
color14 #94e2d5 # Color Cyan

color7 #bac2de # Color White
color15 #a6adc8 # Color White