# Layout
legacy_layout=false
no_display
no_small_font
background_alpha=0.0
position=top-left
table_columns=4
font_size=24
background_color=000000
text_color=FFFFFF
toggle_hud=Shift_R+F12

# CPU
cpu_stats
cpu_temp
cpu_mhz
cpu_text=i7-13700H
cpu_color=7FC7FF

# GPU
gpu_stats
gpu_core_clock
gpu_mem_clock
gpu_temp
gpu_text=UHD Graphics, RTX 4060 MaxQ
gpu_color=ff8244

# VRAM
vram
vram_color=ad64c1

# RAM
ram
ram_color=c26693

# Frames
fps
frame_timing
frametime_color=ffbe6f